---
kind: "operation"
client: "rug-cli 0.19.1"
editor:
  name: "EnableTravisForRugArchiveTS"
  group: "atomist-rugs"
  artifact: "travis-editors"
  version: "0.7.0"
  origin:
    repo: "atomist-rugs/travis-editors.git"
    branch: "master"
    sha: "b910aef*"
  parameters:
    - "repo_slug": "atomist-rugs/spring-cloud-editors"
    - "org": ".org"
    - "github_token": "4**************************************b"
    - "maven_base_url": "https://atomist.jfrog.io/atomist"
    - "maven_user": "t************h"
    - "maven_token": "A***********************************************************************i"

---
kind: "operation"
client: "rug-cli 0.21.0-SNAPSHOT"
executor:
  name: "UpdateRugVersion"
  group: "atomisthqa"
  artifact: "atomist-rugs"
  version: "0.2.5"
  origin:
    repo: "n/a"
    branch: "n/a"
    sha: "n/a"

---
kind: "operation"
client: "rug-cli 0.21.0-SNAPSHOT"
executor:
  name: "UpdateRugVersion"
  group: "atomisthqa"
  artifact: "atomist-rugs"
  version: "0.2.5"
  origin:
    repo: "n/a"
    branch: "n/a"
    sha: "n/a"

---
kind: "operation"
client: "rug-cli 0.23.0"
editor:
  name: "atomist-rugs.rug-editors.AddRugEditor"
  group: "atomist-rugs"
  artifact: "rug-editors"
  version: "0.10.0"
  origin:
    repo: "git@github.com:atomist-rugs/rug-editors.git"
    branch: "addHandlerEditor"
    sha: "b8650ae"
  parameters:
    - "editor_name": "AddSleuth"

---
kind: "operation"
client: "rug-cli 0.23.0"
editor:
  name: "atomist-rugs.rug-editors.AddAtomistCopyrightToRug"
  group: "atomist-rugs"
  artifact: "rug-editors"
  version: "0.10.0"
  origin:
    repo: "git@github.com:atomist-rugs/rug-editors.git"
    branch: "addHandlerEditor"
    sha: "4710877"
  parameters:
    - "path_and_filename": ".atomist/editors/AddSleuth.rug"

---
kind: "operation"
client: "rug-cli 0.23.0"
editor:
  name: "atomist-rugs.rug-editors.AddAtomistCopyrightToRug"
  group: "atomist-rugs"
  artifact: "rug-editors"
  version: "0.10.0"
  origin:
    repo: "git@github.com:atomist-rugs/rug-editors.git"
    branch: "addHandlerEditor"
    sha: "4710877"
  parameters:
    - "path_and_filename": ".atomist/tests/AddSleuth.rt"

